FROM openjdk:21-jdk-slim AS base
COPY perfume-api/build/libs/perfume-api-0.0.1.jar webapp.jar
EXPOSE 8080
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-Djava.security.egd=file:/dev/./urandom", "-jar", "./webapp.jar"]
