spring:
  config:
    activate:
      on-profile: 'default'
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: 'jdbc:mysql://localhost:3307/test'
    username: 'root'
    password: '9409'
    hikari:
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 15000
      leak-detection-threshold: 60000
      pool-name: 'perfume-db-pool'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
#  redis:
#    host: localhost
#    port: 6379
#    password: very-strong-local-redis-password!@#$!%!@#
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 'test'
            client-secret: 'test'
            scope:
              - profile
              - email
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ''
    password: ''
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
whitelist:
  cors:
    - http://localhost:3000

jwt:
  secret-key: 'readaperfumesecretkeyhelloletsmakegoodthings'
  redirect-uri: '/'
  access-token-validity-in-seconds: 7200
  refresh-token-validity-in-seconds: 604800

encryption:
  aes:
    secret-key: 'readaperfumesecretkeyhelloletsmakegoodthings'

flyway:
  enabled: false
  validate-on-migrate: false
