spring:
  config:
    activate:
      on-profile: 'dev'
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      max-lifetime: 1800000
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 15000
      leak-detection-threshold: 60000
      pool-name: 'perfume-db-pool'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_AUTH_PASSWORD}
  data:
    web:
      pageable:
        one-indexed-parameters: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

whitelist:
  cors:
    - http://localhost:3000
    - http://localhost:5173

jwt:
  secret-key: ${JWT_SECRET_KEY}
  redirect-uri: ${JWT_REDIRECT_URI}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

encryption:
  aes:
    secret-key: ${AES_SECRET_KEY}

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
  enable-tracing: true
  send-default-pii: true
  logging:
    minimum-event-level: warn
    minimum-breadcrumb-level: info

flyway:
  enabled: true
  url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  user: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  locations: 'classpath:db/migration'
  validate-on-migrate: true
  baseline-on-migrate: true
  baseline-version: 1
